version: '3'
services:
  app:
    container_name: ci4-app
    build:
      context: ./php
    ports:
      - "80:80"
    volumes:
    - ..:/var/www/html
    links:
      - redis
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
volumes:
  redis-data:

networks:
  app-network:
    driver: bridge